### ISSUE TITLE
Add Windows support

### ISSUE THREAD

**Issue by vweevers** [ralphtheninja/test-for#4]
By using [cross-spawn](https://github.com/moxystudio/node-cross-spawn), which translates `spawn('npm')` into `spawn('npm.cmd')`.

**Comment by ralphtheninja** [comment]
PR welcome :)

**Comment by vweevers** [comment]
@ralphtheninja why does your `package-lock.json` contain carets? If I `npm install` it changes to:

```diff
-        "co": "^4.6.0",
-        "fast-deep-equal": "^1.0.0",
-        "fast-json-stable-stringify": "^2.0.0",
-        "json-schema-traverse": "^0.3.0"
+        "co": "4.6.0",
+        "fast-deep-equal": "1.1.0",
+        "fast-json-stable-stringify": "2.0.0",
+        "json-schema-traverse": "0.3.1"
```

(etc)

**Comment by vweevers** [comment]
Apparently it's a difference between npm 5 (which I was on) and 6: https://github.com/npm/npm/issues/20434
